fdb:
  compiler:
    - toolchain: gcc
      spec: gcc@13.3
  unify: when_possible
  mpi: null
  packages: []
  specs:
    - fdb@=5.18.3 backends=lustre
    - gribjump@=0.10.2
    - eckit@=native linalg=none compression=lz4 +curl +ssl
    - metkit@=1.15.2-levelist
    - eccodes@=native jp2k=none ~fortran +pthreads +aec +geo
    - ecbuild@=3.12.0
    - python@=3.11.6
  variants:
    - ~mpi
  views:
    realtime:
      link: roots
      uenv:
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
    rea-l-ch1:
      link: roots
      uenv:
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
    remote-devt:
      link: roots
      uenv:
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
    remote-depl:
      link: roots
      uenv:
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
